import "./global.css";

import { Metadata } from "next";
import ThemeProvider from "@/components/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: {
    default: "Next.js-15",
    template: "%s | Next.js-15",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ThemeProvider>
          <body>
            <header
              style={{
                backgroundColor: "lightgray",
                padding: "1rem",
              }}
            >
              <p>Header</p>
            </header>
            {children}
            <footer
              style={{
                backgroundColor: "ghostwhite",
                padding: "1rem",
              }}
            >
              <p>Footer</p>
            </footer>
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
}
