import "./global.css";

import { Metadata } from "next";
import ErrorWrapper from "@/app/error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js-15",
    template: "%s | Next.js-15",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightgray",
            padding: "1rem",
          }}
        >
          <p>Header</p>
        </header>
        <ErrorWrapper>{children}</ErrorWrapper>
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
